version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      SECRET_KEY_BASE: d788349df7bf879f1d1b6be919283e6a1f74ea61711c07cea5493d407d3d6239ed7e6e10904a029677d932f7ac1b75d01beecf7f7bae35f94caaaf2ed44b3ea2
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
